/** @type {import('jest').Config} */
module.exports = {
  projects: [
    "<rootDir>/backend/jest.config.js",
    "<rootDir>/frontend/jest.config.js",
  ],
  collectCoverage: true,
  coverageDirectory: "<rootDir>/coverage",
  coverageReporters: ["text", "lcov", "json-summary"],
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "backend/src/index.ts",
    "backend/src/workers/index.ts",
    "backend/src/config/env.ts",
    "backend/src/config/redis.ts",
    "backend/src/config/supabase.ts",
    "backend/src/routes/",
    "backend/src/queues/",
    "backend/src/services/integrations/gmail/index.ts",
    "backend/src/services/integrations/jira/index.ts",
    "backend/src/services/integrations/jira/client.ts",
    "backend/src/services/integrations/google/client.ts",
    "backend/src/services/integrations/google-calendar/",
    "backend/src/services/integrations/discord/",
    "backend/src/services/integrations/slack/",
    "backend/src/services/integrations/index.ts",
    "backend/src/services/oauth/discord.ts",
    "backend/src/services/oauth/slack.ts",
    "backend/src/services/oauth/jira.ts",
    "backend/src/models/push-subscription.model.ts",
    "frontend/src/middleware.ts",
    "frontend/src/app/",
    "frontend/src/lib/push.ts",
    "frontend/src/components/ui/delete.tsx",
    "frontend/src/hooks/usePushNotifications.ts",
    "frontend/src/hooks/useServiceWorker.ts",
    "frontend/src/lib/service-worker.ts",
    "frontend/src/lib/query-persister.ts",
    "frontend/src/lib/supabase/server.ts",
    "frontend/src/lib/supabase/client.ts",
  ],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
};
