/** @type {import('jest').Config} */
module.exports = {
  displayName: "backend",
  preset: "ts-jest",
  testEnvironment: "node",
  rootDir: __dirname,
  setupFiles: ["<rootDir>/jest.setup.ts"],
  testMatch: ["<rootDir>/src/**/*.test.ts", "<rootDir>/__tests__/**/*.test.ts"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
  },
  transform: {
    "^.+\\.tsx?$": [
      "ts-jest",
      {
        isolatedModules: true,
        diagnostics: false,
      },
    ],
  },
  collectCoverageFrom: [
    "<rootDir>/src/**/*.ts",
    "!<rootDir>/src/index.ts",
    "!<rootDir>/src/workers/index.ts",
  ],
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "<rootDir>/src/index.ts",
    "<rootDir>/src/workers/index.ts",
    "<rootDir>/src/config/env.ts",
    "<rootDir>/src/config/redis.ts",
    "<rootDir>/src/config/supabase.ts",
    "<rootDir>/src/routes/",
    "<rootDir>/src/queues/",
    "<rootDir>/src/services/integrations/gmail/index.ts",
    "<rootDir>/src/services/integrations/jira/index.ts",
    "<rootDir>/src/services/integrations/jira/client.ts",
    "<rootDir>/src/services/integrations/google/client.ts",
    "<rootDir>/src/services/integrations/google-calendar/",
    "<rootDir>/src/services/integrations/discord/",
    "<rootDir>/src/services/integrations/slack/",
    "<rootDir>/src/services/integrations/index.ts",
    "<rootDir>/src/services/oauth/discord.ts",
    "<rootDir>/src/services/oauth/slack.ts",
    "<rootDir>/src/services/oauth/jira.ts",
    "<rootDir>/src/models/push-subscription.model.ts",
    "<rootDir>/src/models/task.model.ts",
    "<rootDir>/src/models/integration.model.ts",
    "<rootDir>/src/services/ai/extractor.ts",
    "<rootDir>/src/services/notifications/push.service.ts",
    "<rootDir>/src/services/integrations/gmail/process-message.ts",
    "<rootDir>/src/services/integrations/jira/process-issue.ts",
    "<rootDir>/src/middlewares/auth.middleware.ts",
  ],
};
